### ISSUE TITLE
Badges to not appear

### ISSUE THREAD

**Issue by invisyarcticfox** [John-Fries-J/Badges-plugin#2]
i think this is due to a new discord update, but badges do not appear anywhere. not in popouts, not in the account menu, nowhere

**Comment by John-Fries-J** [comment]
Leaving this open. I'm working on a fix!

**Comment by kidd0x** [comment]
Did you find a fix?

**Comment by John-Fries-J** [comment]
Yes, Editing how it is configured with a GUI then a new update will be released!

**Comment by 0xQueen** [comment]
@John-Fries-J any updates on this?

**Comment by John-Fries-J** [comment]
Still having issues with the actual implementation. I've been dissecting how discord applies badges for a few weeks now but it's quite hard. Someone in the discord mentioned that they got the plugin working, so I'll either have a look at their approach or continue with mine.

**Comment by 0xQueen** [comment]
@John-Fries-J Here you go, this is a script I found made by someone within the Discord Experiments server, but I made it slightly easier to read and added some missing badges.

Hopefully this will give you an easier start.

```js
let chunk =
  (webpackChunkdiscord_app.push([
    [""],
    {},
    (e) => {
      m = [];
      for (let chunk in e.c) m.push(e.c[chunk]);
    },
  ]),
  m);

let user = chunk
  .find((m) => m?.exports?.default?.getCurrentUser)
  .exports.default.getCurrentUser();

let userProfile = chunk.find((m) => m?.exports?.default?.getUserProfile).exports
  .default;

function assignBadges() {
  let profile = userProfile.getUserProfile(user.id);
  
  profile.badges = [
    {
      id: "staff",
      description: "Discord Staff",
      icon: "5e74e9b61934fc1f67c65515d1f7e60d",
      link: "https://discord.com/company",
    },
    {
      id: "partner",
      description: "Partnered Server Owner",
      icon: "3f9748e53446a137a052f3454e2de41e",
      link: "https://discord.com/partners",
    },
    {
      id: "certified_moderator",
      description: "Moderator Programs Alumni",
      icon: "fee1624003e2fee35cb398e125dc479b",
      link: "https://discord.com/safety",
    },
    {
      id: "hypesquad",
      description: "HypeSquad Events",
      icon: "bf01d1073931f921909045f3a39fd264",
      link: "https://discord.com/hypesquad",
    },
    {
      id: "hypesquad_house_1",
      description: "HypeSquad Bravery",
      icon: "8a88d63823d8a71cd5e390baa45efa02",
      link: "https://discord.com/settings/hypesquad-online",
    },
    {
      id: "hypesquad_house_2",
      description: "HypeSquad Brilliance",
      icon: "011940fd013da3f7fb926e4a1cd2e618",
      link: "https://discord.com/settings/hypesquad-online",
    },
    {
      id: "hypesquad_house_3",
      description: "HypeSquad Balance",
      icon: "3aa41de486fa12454c3761e8e223442e",
      link: "https://discord.com/settings/hypesquad-online",
    },
    {
      id: "bug_hunter_level_1",
      description: "Discord Bug Hunter",
      icon: "2717692c7dca7289b35297368a940dd0",
      link: "https://support.discord.com/hc/en-us/articles/360046057772-Discord-Bugs",
    },
    {
      id: "bug_hunter_level_2",
      description: "Discord Bug Hunter",
      icon: "848f79194d4be5ff5f81505cbd0ce1e6",
      link: "https://support.discord.com/hc/en-us/articles/360046057772-Discord-Bugs",
    },
    {
      id: "active_developer",
      description: "Active Developer",
      icon: "6bdc42827a38498929a4920da12695d9",
      link: "https://support-dev.discord.com/hc/en-us/articles/10113997751447?ref=badge",
    },
    {
      id: "verified_developer",
      description: "Early Verified Bot Developer",
      icon: "6df5892e0f35b051f8b61eace34f4967",
    },
    {
      id: "early_supporter",
      description: "Early Supporter",
      icon: "7060786766c9c840eb3019e725d2b358",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "premium",
      description: "Subscriber since Dec 22, 2016",
      icon: "2ba85e8026a8614b640c2837bcdfe21b",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl1",
      description: "Server boosting since May 4, 2023",
      icon: "51040c70d4f20a921ad6674ff86fc95c",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl2",
      description: "Server boosting since Mar 11, 2023",
      icon: "0e4080d1d333bc7ad29ef6528b6f2fb7",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl3",
      description: "Server boosting since Feb 23, 2023",
      icon: "72bed924410c304dbe3d00a6e593ff59",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl4",
      description: "Server boosting since Sep 17, 2022",
      icon: "df199d2050d3ed4ebf84d64ae83989f8",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl5",
      description: "Server boosting since Aug 1, 2022",
      icon: "996b3e870e8a22ce519b3a50e6bdd52f",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl6",
      description: "Server boosting since Mar 26, 2022",
      icon: "991c9f39ee33d7537d9f408c3e53141e",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl7",
      description: "Server boosting since Feb 4, 2022",
      icon: "cb3ae83c15e970e8f3d410bc62cb8b99",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl8",
      description: "Server boosting since Nov 26, 2021",
      icon: "7142225d31238f6387d9f09efaa02759",
      link: "https://discord.com/settings/premium",
    },
    {
      id: "guild_booster_lvl9",
      description: "Server boosting since Sep 6, 2020",
      icon: "ec92202290b48d0879b7413d2dde3bab",
      link: "https://discord.com/settings/premium",
    },
    { // You must turn "Legacy Username Badge" on from Profiles settings.
      id: "legacy_username",
      description: "Originally known as " + profile.legacyUsername,
      icon: "6de6d34650760ba5551a79732e98ed60",
    }, 
    {
      id: "bot_commands",
      description: "Supports Commands",
      icon: "6f9e37f9029ff57aef81db857890005e",
      link: "https://discord.com/blog/welcome-to-the-new-era-of-discord-apps?ref=badge",
    },
    {
      id: "automod",
      description: "Uses automod",
      icon: "f2459b691ac7453ed6039bbcfaccbfcd",
    },
    {
      id: "application_guild_subscription",
      description: "This server has " + user.username + " Premium",
      icon: "d2010c413a8da2208b7e4f35bd8cd4ac",
    },
  ];

  console.log(
    "'assignBadges' has been enabled.\n\nNote: If the badges reset use `assignBadges()` in the console."
  );
}

assignBadges();
```

**Comment by John-Fries-J** [comment]
Testing now

**Comment by John-Fries-J** [comment]
It works. Fixing it so it auto applies and also re applies when it gets disabled.

**Comment by 0xQueen** [comment]
Enjoy, haven't made it, only found it by accident.

**Comment by Lucknite** [comment]
it says META was not found

**Comment by 0xQueen** [comment]
![image](https://github.com/John-Fries-J/Badges-plugin/assets/156551265/df0c323d-fbea-4d6d-83d7-de29c784bc8c)
Still works for me

**Comment by Sciccorz** [comment]
> ![image](https://private-user-images.githubusercontent.com/156551265/327288710-df0c323d-fbea-4d6d-83d7-de29c784bc8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzc2NjAsIm5iZiI6MTcxNjE3NzM2MCwicGF0aCI6Ii8xNTY1NTEyNjUvMzI3Mjg4NzEwLWRmMGMzMjNkLWZiZWEtNGQ2ZC04M2Q3LWRlMjljNzg0YmM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMzU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmFmNDUxZmI1MjdkZjVlMzg0ZGNmNTlmMGE0OTA1YjE3OWY0NjI1YTMzMTNlZTVlMDJjZGJlN2U4MzZiMjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eBQ8Zhv1Kl-a10vDQdF0qTNwBB28arf6RFRSsRrVFWo) Still works for me

sorry, could you explain how you put your script into the plugin? I want to do it but can't figure it out and keep getting errors

**Comment by 0xQueen** [comment]
> > ![image](https://private-user-images.githubusercontent.com/156551265/327288710-df0c323d-fbea-4d6d-83d7-de29c784bc8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzc2NjAsIm5iZiI6MTcxNjE3NzM2MCwicGF0aCI6Ii8xNTY1NTEyNjUvMzI3Mjg4NzEwLWRmMGMzMjNkLWZiZWEtNGQ2ZC04M2Q3LWRlMjljNzg0YmM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMzU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmFmNDUxZmI1MjdkZjVlMzg0ZGNmNTlmMGE0OTA1YjE3OWY0NjI1YTMzMTNlZTVlMDJjZGJlN2U4MzZiMjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eBQ8Zhv1Kl-a10vDQdF0qTNwBB28arf6RFRSsRrVFWo) Still works for me
> 
> sorry, could you explain how you put your script into the plugin? I want to do it but can't figure it out and keep getting errors

Hey, I don't use JavaScript as much, and I haven't programmed the script, You can still however send me the script you made & I can fix it, however I'm more skilled in Assembly, Rust & Python.

**Comment by Sciccorz** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/156551265/327288710-df0c323d-fbea-4d6d-83d7-de29c784bc8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzc2NjAsIm5iZiI6MTcxNjE3NzM2MCwicGF0aCI6Ii8xNTY1NTEyNjUvMzI3Mjg4NzEwLWRmMGMzMjNkLWZiZWEtNGQ2ZC04M2Q3LWRlMjljNzg0YmM4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMzU2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmFmNDUxZmI1MjdkZjVlMzg0ZGNmNTlmMGE0OTA1YjE3OWY0NjI1YTMzMTNlZTVlMDJjZGJlN2U4MzZiMjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eBQ8Zhv1Kl-a10vDQdF0qTNwBB28arf6RFRSsRrVFWo) Still works for me
> 
> > 
> 
> > sorry, could you explain how you put your script into the plugin? I want to do it but can't figure it out and keep getting errors
> 
> 
> 
> Hey, I don't use JavaScript as much, and I haven't programmed the script, You can still however send me the script you made & I can fix it, however I'm more skilled in Assembly, Rust & Python.

I have 0 programming experience and just stumbled across this code. Would I just paste the code you posted into the custom css terminal for Better Discord? Because when I try that nothing happens and it just shows a bunch of errors.

**Comment by John-Fries-J** [comment]
> I have 0 programming experience and just stumbled across this code. Would I just paste the code you posted into the custom css terminal for Better Discord? Because when I try that nothing happens and it just shows a bunch of errors.

You can just paste this into your developer console on discord. Should work, but I haven't tried for a while personally.

**Comment by Sciccorz** [comment]
> > I have 0 programming experience and just stumbled across this code. Would I just paste the code you posted into the custom css terminal for Better Discord? Because when I try that nothing happens and it just shows a bunch of errors.
> 
> You can just paste this into your developer console on discord. Should work, but I haven't tried for a while personally.

![image](https://github.com/John-Fries-J/Badges-plugin/assets/140935674/acb57b3e-fe07-4744-a648-f3fd230e8381)
This is all I see, using Better Discord's direct css editor

**Comment by John-Fries-J** [comment]
This is using bd css editor. Like I said you need to use devtools. F12 or ctrl + shift + i

**Comment by Sciccorz** [comment]
> This is using bd css editor. Like I said you need to use devtools. F12 or ctrl + shift + i

I enabled dev tools with bd and turned on dev mode in the main settings but when i press ctrl shift i nothing happens
I am using the stable desktop app if that helps
![image](https://github.com/John-Fries-J/Badges-plugin/assets/140935674/7c76a3b3-f991-4616-97ea-ba3ff2305e6e)

**Comment by Sciccorz** [comment]
> > This is using bd css editor. Like I said you need to use devtools. F12 or ctrl + shift + i
> 
> 
> 
> I enabled dev tools with bd and turned on dev mode in the main settings but when i press ctrl shift i nothing happens
> 
> I am using the stable desktop app if that helps
> 
> ![image](https://github.com/John-Fries-J/Badges-plugin/assets/140935674/7c76a3b3-f991-4616-97ea-ba3ff2305e6e)
> 
> 

Tried the same thing in ptb and no difference

**Comment by meshoksnega** [comment]
Error
`Discord Badges v1.0.2 could not be started. TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (Badges.plugin.js:41:40)
    at r (sentry.765b00e66783ff42fca1.js:1:1999)
    at l.handlePush (renderer.js:5:49385)
    at WebpackModules.handlePush (0PluginLibrary.plugin.js:3189:24)
    at eval (Badges.plugin.js:40:37)
    at module.exports.start (Badges.plugin.js:47:11)
    at N.startPlugin (renderer.js:5:29250)
    at N.startAddon (renderer.js:5:29043)
    at N.enableAddon (renderer.js:5:7726)
    at N.toggleAddon (renderer.js:5:8525)
    at N.togglePlugin (renderer.js:5:26331)
    at renderer.js:5:92815
    at renderer.js:5:124976
    at Object.eB (2160.5b1de8a086b42fe36070.js:12:853572)
    at eG (2160.5b1de8a086b42fe36070.js:12:853726)
    at 2160.5b1de8a086b42fe36070.js:12:872035
    at re (2160.5b1de8a086b42fe36070.js:12:872134)
    at rt (2160.5b1de8a086b42fe36070.js:12:872548)
    at 2160.5b1de8a086b42fe36070.js:12:878010
    at sA (2160.5b1de8a086b42fe36070.js:12:935067)
    at eI (2160.5b1de8a086b42fe36070.js:12:852710)
    at rs (2160.5b1de8a086b42fe36070.js:12:873839)
    at tB (2160.5b1de8a086b42fe36070.js:12:859507)
    at tP (2160.5b1de8a086b42fe36070.js:12:859291)`

**Comment by meshoksnega** [comment]
It's means what it can't load
Code:
```
Discord Badges v1.0.2 could not be started. TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at eval (Badges.plugin.js:41:40)
    at r (sentry.765b00e66783ff42fca1.js:1:1999)
    at l.handlePush (renderer.js:5:49385)
    at WebpackModules.handlePush (0PluginLibrary.plugin.js:3189:24)
    at eval (Badges.plugin.js:40:37)
    at module.exports.start (Badges.plugin.js:47:11)
    at N.startPlugin (renderer.js:5:29250)
    at N.startAddon (renderer.js:5:29043)
    at N.enableAddon (renderer.js:5:7726)
    at N.toggleAddon (renderer.js:5:8525)
    at N.togglePlugin (renderer.js:5:26331)
    at renderer.js:5:92815
    at renderer.js:5:124976
    at Object.eB (2160.5b1de8a086b42fe36070.js:12:853572)
    at eG (2160.5b1de8a086b42fe36070.js:12:853726)
    at 2160.5b1de8a086b42fe36070.js:12:872035
    at re (2160.5b1de8a086b42fe36070.js:12:872134)
    at rt (2160.5b1de8a086b42fe36070.js:12:872548)
    at 2160.5b1de8a086b42fe36070.js:12:878010
    at sA (2160.5b1de8a086b42fe36070.js:12:935067)
    at eI (2160.5b1de8a086b42fe36070.js:12:852710)
    at rs (2160.5b1de8a086b42fe36070.js:12:873839)
    at tB (2160.5b1de8a086b42fe36070.js:12:859507)
    at tP (2160.5b1de8a086b42fe36070.js:12:859291)
```

**Comment by meshoksnega** [comment]
@John-Fries-J

**Comment by meshoksnega** [comment]
@John-Fries-J

**Comment by John-Fries-J** [comment]
> @John-Fries-J

Bro, Read the readme.md. It says the plugin DOES NOT WORK. THERE WILL BE A FIX WHEN I AM LESS BUSY. As for getting this to work. You need to copy and paste the script into your dev console like we've said before. 

As for this issue tracker. I'm going to close it as it just promps dumb stuff. If you continue to have an issue join the discord and ask for help.

**Comment by Sciccorz** [comment]
@0xQueen I get this when i run the script "Uncaught TypeError: Cannot read properties of undefined (reading 'exports')" how do i fix it
