### ISSUE TITLE
I think i found a fix probably

### ISSUE THREAD

**Issue by Mata0777** [John-Fries-J/Badges-plugin#4]
Hello i think i find a fix theres a plugin that adds one custom badge i think that you can get the code from the plugin the plugin link is here : https://github.com/riolubruh/YABDP4Nitro it adds a custom badge so i think that you can just copy paste a part of the code of the plugin and add the badges back that way if it works just comment.

**Comment by John-Fries-J** [comment]
This could be done but would not achieve how it should be done properly
